path:  #ruta de la carpeta data
train: images/train #ruta de las imagenes
val: images/val #ruta de los valores de las imagenes
test: images/test #ruta de las imagenes de test

# Clases
names:
  0: license_plate